#!/usr/bin/env python3
"""Regenerate the Data & AI diagrams from the palette + templates.

Single source of truth:
  - colors   -> brand_palette.json
  - structure-> *.mmd.tpl  ({{token}} placeholders); one entry per diagram in DIAGRAMS

Outputs per diagram (generated — do NOT hand-edit):
  - <name>.mmd   raw Mermaid (mmdc / VS Code / mermaid.live)
  - <name>.md    fenced ```mermaid``` block (renders inline on GitHub)
  - <name>.svg   transparent-background vector — only if `mmdc` (mermaid-cli) is on PATH
  - <name>.png   white-background raster (2x scale) — only if `mmdc` is on PATH

Usage:  python docs/diagrams/render.py
Stdlib only; no third-party dependencies.
"""

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PALETTE = HERE / "brand_palette.json"

# Each diagram: (template stem, human title for the .md heading).
# Outputs derive from the stem: <stem>.mmd / <stem>.md / <stem>.svg
DIAGRAMS = [
    ("agent_operating_model", "Data & AI — Agent Operating Model"),
    ("glue_job_monitor", "Glue Job Monitor — Implementation Options"),
]

TOKEN_RE = re.compile(r"\{\{\s*([a-zA-Z0-9_]+)\s*\}\}")

GENERATED_HEADER = (
    "<!-- GENERATED by docs/diagrams/render.py — do NOT edit by hand.\n"
    "     Edit brand_palette.json (colors) or agent_operating_model.mmd.tpl (structure),\n"
    "     then run: python docs/diagrams/render.py -->\n"
)


def load_colors() -> dict:
    data = json.loads(PALETTE.read_text(encoding="utf-8"))
    colors = data.get("colors", {})
    if not colors:
        sys.exit(f"ERROR: no 'colors' object found in {PALETTE.name}")
    return colors


def render_template(template: str, colors: dict) -> str:
    unknown: set[str] = set()

    def sub(match: re.Match) -> str:
        key = match.group(1)
        if key not in colors:
            unknown.add(key)
            return match.group(0)
        return colors[key]

    result = TOKEN_RE.sub(sub, template)
    leftover = TOKEN_RE.findall(result)
    if unknown or leftover:
        missing = sorted(unknown or set(leftover))
        sys.exit(
            "ERROR: unresolved template tokens (add them to brand_palette.json "
            f"'colors'): {', '.join(missing)}"
        )
    return result


# Extra mmdc flags per output format. Key = file extension.
IMAGE_FORMATS = {
    "svg": ["-b", "transparent"],
    "png": ["-b", "white", "-s", "2"],
}


def render_image(mmdc: str, out_mmd: Path, out_img: Path, extra_args: list) -> bool:
    try:
        subprocess.run(
            [mmdc, "-i", str(out_mmd), "-o", str(out_img), *extra_args],
            check=True,
        )
        return True
    except (subprocess.CalledProcessError, OSError) as exc:
        print(f"WARN: mmdc found but {out_img.suffix.lstrip('.')} render "
              f"failed for {out_mmd.name}: {exc}")
        return False


def render_diagram(stem: str, title: str, colors: dict) -> None:
    template = HERE / f"{stem}.mmd.tpl"
    out_mmd = HERE / f"{stem}.mmd"
    out_md = HERE / f"{stem}.md"

    if not template.exists():
        sys.exit(f"ERROR: template not found: {template}")

    mermaid = render_template(template.read_text(encoding="utf-8"), colors).rstrip() + "\n"

    out_mmd.write_text(mermaid, encoding="utf-8")
    out_md.write_text(
        f"{GENERATED_HEADER}\n# {title}\n\n```mermaid\n{mermaid}```\n",
        encoding="utf-8",
    )

    print(f"wrote {out_mmd.relative_to(HERE.parent.parent)}")
    print(f"wrote {out_md.relative_to(HERE.parent.parent)}")

    mmdc = shutil.which("mmdc")
    if not mmdc:
        return
    for ext, extra_args in IMAGE_FORMATS.items():
        out_img = HERE / f"{stem}.{ext}"
        if render_image(mmdc, out_mmd, out_img, extra_args):
            print(f"wrote {out_img.relative_to(HERE.parent.parent)}")


def main() -> None:
    colors = load_colors()
    for stem, title in DIAGRAMS:
        render_diagram(stem, title, colors)

    if not shutil.which("mmdc"):
        print(
            "note: 'mmdc' not found — skipped SVG/PNG. To view/export a diagram:\n"
            "      - GitHub: open <name>.md (renders inline)\n"
            "      - VS Code: open .mmd with the Mermaid preview extension\n"
            "      - Web: paste .mmd into https://mermaid.live\n"
            "      - SVG/PNG: npm i -g @mermaid-js/mermaid-cli, then re-run this script"
        )


if __name__ == "__main__":
    main()
